### ISSUE TITLE
Add category page

### ISSUE THREAD

**Issue by duranmla** [debtcollective/community#29]
**What:** Add the category page (list of topics within a category)
![image](https://user-images.githubusercontent.com/1425162/72453083-d9772700-37be-11ea-831d-ce036e4e0082.png)

[Category page design](https://sketch.cloud/s/54jwx/a/O4800v)
[Category page show more design](https://sketch.cloud/s/54jwx/a/DMYddk)

## Tasks

- ~Display preview content~ #34 
- [x] Display all the topics within a category
- [x] Check related topics not broken
- [x] Replace mobile template too https://github.com/debtcollective/discourse-debtcollective-theme/pull/17
- [x] Add "show more" functionality https://github.com/debtcollective/discourse-debtcollective-theme/pull/18
- ~Add the "Join collective" banner~ #35

**Comment by duranmla** [comment]
There are no built-in support for topics description. https://meta.discourse.org/t/get-excerpt-for-regular-topics/33482/5 I will work without it for now.

**Comment by duranmla** [comment]
I see we are having this behaviour on related topics
![image](https://user-images.githubusercontent.com/1425162/73837342-8caccc00-4811-11ea-92e9-63f350619815.png)

We need to address that before close the ticket.

**Comment by duranmla** [comment]
I have another branch with the "show more"feature implemented but I would like to have the current pull request reviewed so I can merge. Key code for the show more at: 726f3e5 and 4b01e71
